import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Icon Endpoint</h1>

        <p className={styles.description}>
          Get started by visiting{" "}
          <a href="https://icogen.vercel.app/api/icon">
            <code className={styles.code}>
              https://icogen.vercel.app/api/icon
            </code>
          </a>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/EvanBacon/app-icon-endpoint"
          target="_blank"
          rel="noopener noreferrer"
        >
          View Source Code
        </a>
      </footer>
    </div>
  );
}
